---

name: pp_liteseg_without_argmax

gops: [19.254271872]
shapes:
  - [1, 3, 512, 512]

mlir_transform:
  model_transform.py 
    --model_name $(name) 
    --model_def $(home)/pp_liteseg.onnx 
    --input_shapes [[1,3,512,512]] 
    --mean 0.0,0.0,0.0 
    --scale 0.0039216,0.0039216,0.0039216 
    --keep_aspect_ratio 
    --pixel_format rgb 
    --output_names bilinear_interp_v2_6.tmp_0 
    --test_input $(root)/dataset/samples/dog.jpg 
    --test_result $(workdir)/$(name)_top_outputs.npz 
    --mlir $(workdir)/$(name).mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/$(name).mlir 
#     --dataset ../ILSVRC2012 
#     --input_num 100 
#     -o $(workdir)/$(name)_cali_table

deploy:
  - model_deploy.py 
      --mlir $(workdir)/$(name).mlir 
      --quantize F32 
      --chip bm1684x 
      --test_input $(workdir)/$(name)_in_f32.npz 
      --test_reference $(workdir)/$(name)_top_outputs.npz 
      --model $(workdir)/$(name)_1684x_f32.bmodel

  - model_deploy.py 
      --mlir $(workdir)/$(name).mlir 
      --quantize INT8 
      --calibration_table $(home)/cali_table 
      --chip bm1684x 
      --test_input $(workdir)/$(name)_in_f32.npz 
      --test_reference $(workdir)/$(name)_top_outputs.npz 
      --tolerance 0.85,0.45 
      --model $(workdir)/$(name)_1684x_int8_sym.bmodel