---

name: TransformerLM

model: $(home)/TransformerLM.pt

time: true
precision: true
runtime_cmp: false

BM1684X:
  build_env:
    - BMCOMPILER_FORCE_GLOBAL_LAYER_BY_ID=a
    - BMCOMPILER_BFLOAT16_LAYER_TYPES=BROADCAST_BINARY(MUL),ELTWISE_BINARY(MUL),
      ACTIVE(SQUARE),BATCH_MATMUL,CONST_BINARY(MUL)

  fp_compile_options:
    python3 -m bmnetp
    --model $(model)
    --shapes '[20,49,128],[20,49,49],[20,48,512],[20,48,512],
      [20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512],[20,48,512]'
    --target $(target)
    --enable_profile True
    --opt 2
    --dyn True
    --cmp 0
