---

name: TransformerDecoder

model: $(home)/TransformerDecoder.pt

time: true
precision: true
runtime_cmp: false

BM1684X:
  build_env:
    - BMCOMPILER_FORCE_GLOBAL_LAYER_BY_ID=a
    - BMCOMPILER_BFLOAT16_LAYER_TYPES=BROADCAST_BINARY(MUL),
      ELTWISE_BINARY(MUL),ACTIVE(SQUARE),BATCH_MATMUL,CONST_BINARY(MUL)

  fp_compile_options:
    python3 -m bmnetp
    --model $(model)
    --shapes '[20,49,256],[1,49,49],[20,458,256],[20,48,256],
      [20,48,256],[20,48,256],[20,48,256],[20,48,256],[20,48,256]'
    --target $(target)
    --enable_profile True
    --opt 2
    --dyn True
    --cmp 0
