---

name: PP-OCRv3cls
gops: 0.05

model: $(home)/ch_ppocr_mobile_v2.0_cls_infer/

fp_batch_sizes: [1, 4, 8, 16]

BM1684X:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32
    - build_env:
        - BMCOMPILER_LAYER_DTYPE_MODE=auto
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      fp_outdir_template: "{}b.fp16.compilation"
      prec: FP16

BM1684:
  fp_loops:
    - build_env:
        - BMCOMPILER_GROUP_SEARCH_COUNT=1
      fp_outdir_template: "{}b.fp32.compilation"
      prec: FP32

fp_compile_options:
  python3 -m bmpaddle 
  --model $(model)
  --net_name $(name)
  --input_names "x"
  --output_names "softmax_0.tmp_0"
  --shapes [1,3,128,128]
  --target $(target)
  --cmp True
  --enable_profile True

time_only_cali:
  python3 -m ufw.cali.cali_model
    --model=$(model)/inference.pdmodel
    --input_shapes="[1,3,128,128]"
    --net_name=$(name)
    --input_names="x"
    --output_names="softmax_0.tmp_0"
    --cali_iterations=200
    --target=$(target)
    --test_iterations=1
    --debug_cmd="not_call_bmnetu;not_suspend;use_fake_data_to_test"

int8_model: $(workdir)/$(name)_bmpaddle_deploy_int8_unique_top.prototxt
int8_weight: $(workdir)/$(name)_bmpaddle.int8umodel
bmnetu_batch_sizes: [1, 4, 8, 16]
bmnetu_options:
  --model $(int8_model)
  --weight $(int8_weight)
  --target $(target)
  --enable_profile True
  --cmp True

build_env:
  - BMCOMPILER_GROUP_SEARCH_COUNT=1
