---

name: tpu-mlir_yoloface

gops: [7.6]

shapes:
  - [1, 3, 736, 736]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/yoloface.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --mean 0.0,0.0,0.0
    --scale 0.0039216,0.0039216,0.0039216
    --pixel_format rgb
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(coco2017_mlir_cali_set)
    --input_num 100
    -o $(home)/cali_table

deploy:
  - model_deploy.py  --mlir $(workdir)/transformed.mlir
      --quantize F32
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --calibration_table $(home)/cali_table
      --quant_input
      --quant_output
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.85,0.45
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
  - model_deploy.py --mlir $(workdir)/transformed.mlir
    --quantize INT8
    --asymmetric
    --calibration_table $(home)/cali_table
    --chip bm1684x
    --test_input $(workdir)/$(name)_in_f32.npz
    --test_reference $(name)_top_outputs.npz
    --tolerance 0.90,0.55
    --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel